Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,6 +5,24 @@ version: 2.1
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
 jobs:
+  check-dnm:
+    # check if "Do Not Merge" label is applied, and prevent merging if it is
+    docker:
+      - image: cimg/base:current
+    steps:
+      - run:
+          name: Check for "Do Not Merge" label
+          command: |
+            pr_number=$(echo $CIRCLE_PULL_REQUEST | awk -F '/' '{print $NF}')
+            labels=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
+            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${pr_number}/labels)
+
+            if echo "$labels" | grep -q "Do Not Merge"; then
+              echo "Label 'Do Not Merge' is present. Failing the job."
+              exit 1  # Fail the job if the label is present
+            else
+              echo "No 'Do Not Merge' label found. Proceeding."
+            fi
   say-hello:
     # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
     # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
@@ -29,3 +47,4 @@ workflows:
     # Inside the workflow, you define the jobs you want to run.
     jobs:
       - say-hello
+      - check-do-not-merge-label
